## name: ayu-dark
## Ayu palette remapped: keyword, func, tag, entity as primary ANSI colors
background = #0d1017
foreground = #bfbdb6
selection-background = #1a3350
selection-foreground =
cursor-color = #ff8f40
cursor-text = #0d1017
palette = 0=#1b1f29
palette = 1=#f06b73
palette = 2=#39bae6
palette = 3=#ffb454
palette = 4=#39bae6
palette = 5=#ff8f40
palette = 6=#39bae6
palette = 7=#c7c7c7
palette = 8=#686868
palette = 9=#f07178
palette = 10=#59c2ff
palette = 11=#e6b450
palette = 12=#59c2ff
palette = 13=#e6b450
palette = 14=#59c2ff
palette = 15=#ffffff
